### ISSUE TITLE
Unable to run the browser version

### ISSUE THREAD

**Issue by Raj123456788** [colinbdclark/osc.js-examples#3]
Missing script start error in electron.  Newbie for  electron can you just explain steps in detail. Unable to run the  electron examples on Windows platform.

**Comment by colinbdclark** [comment]
Electron provides a very helpful [Quick Start tutorial](https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md). I recommend starting with that and getting comfortable with the basic requirements and idioms of developing Electron applications.

Using osc.js with it should be no different than any other Node.js library (if you're using osc.js in the Electron main thread) and, in the Browser process for each window, the same as with any other web page.

Unfortunately, I'm not sure I can provide specific help or examples with the issue you're encountering, since you haven't provided any details about how you're using osc.js with Electron.

**Comment by Raj123456788** [comment]
Thank you for the response Colin. I am trying to find answer for this question: http://stackoverflow.com/questions/35167173/unable-to-run-a-screen-share-chrome-app-using-electron/35237919#35237919

I would appreciate if you can answer my question and guide me where am I going wrong? Appreciate your help Thanks!

**Comment by colinbdclark** [comment]
Hi again,

I'm afraid I can't provide any insights into the problem you're having. It doesn't sound like it is related at all to osc.js or Open Sound Control, so I'm going to go ahead and close this issue. 

Good luck finding a solution to your issue! It looks like you've posted in the right forums on Stack Overflow and the Electron forum; hopefully someone there will be able to help you.
